name: Deploy Lambda function

on:
  push:
    branches:
      - main

jobs:
  unittest:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.lock
      - name: Run unittests
        run: python -m unittest -v

  deploy:
    runs-on: ubuntu-latest
    needs: [ unittest ]
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Update Lambda function code
        run: |
          mkdir twitter-ainouta-bot
          cd twitter-ainouta-bot
          python -m pip install -t ./ -r ../requirements.lock
          cp ../lambda_function.py .
          zip -r twitter-ainouta-bot.zip ./

          aws lambda update-function-code \
              --function-name twitter-ainouta-bot \
              --zip-file fileb://twitter-ainouta-bot.zip | \
            jq 'del(.Environment, .FunctionArn, .Role)'
